CREATE TYPE "public"."sprint_task_event" AS ENUM('complete', 'uncomplete', 'skip', 'unskip', 'promote', 'pull');--> statement-breakpoint
CREATE TYPE "public"."sprint_task_status" AS ENUM('assigned', 'completed', 'deferred', 'abandoned');--> statement-breakpoint
CREATE TYPE "public"."task_complexity" AS ENUM('trivial', 'simple', 'default', 'complex');--> statement-breakpoint
CREATE TYPE "public"."task_priority" AS ENUM('critical', 'urgent', 'default', 'deferred', 'optional');--> statement-breakpoint
CREATE TABLE "client_migrations" (
	"tag" text PRIMARY KEY NOT NULL,
	"applied_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "focus_sessions" (
	"uid" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "focus_sessions_uid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "projects" (
	"uid" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "projects_uid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"description" text,
	"image" text
);
--> statement-breakpoint
CREATE TABLE "sprint_task_events" (
	"uid" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "sprint_task_events_uid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sprint_id" integer NOT NULL,
	"task_id" integer NOT NULL,
	"timestamp" timestamp with time zone DEFAULT now() NOT NULL,
	"event" "sprint_task_event" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sprint_tasks" (
	"sprint_id" integer NOT NULL,
	"task_id" integer NOT NULL,
	"status" "sprint_task_status" DEFAULT 'assigned' NOT NULL,
	"added_at" timestamp with time zone DEFAULT now() NOT NULL,
	"ordinal" integer NOT NULL,
	CONSTRAINT "sprint_tasks_sprint_id_task_id_pk" PRIMARY KEY("sprint_id","task_id")
);
--> statement-breakpoint
CREATE TABLE "sprints" (
	"uid" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "sprints_uid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"session_id" integer,
	"duration_minutes" integer NOT NULL,
	"recovery_time_minutes" integer,
	"scheduled_start" timestamp with time zone,
	"ordinal" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"started_at" timestamp with time zone,
	"ended_at" timestamp with time zone,
	CONSTRAINT "positive_duration" CHECK ("sprints"."duration_minutes" > 0)
);
--> statement-breakpoint
CREATE TABLE "tasks" (
	"uid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tasks_uid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"project_id" integer,
	"parent_task_id" integer,
	"title" text NOT NULL,
	"description" text,
	"priority" "task_priority",
	"complexity" "task_complexity",
	CONSTRAINT "no_task_as_own_parent" CHECK ("tasks"."uid" IS DISTINCT FROM "tasks"."parent_task_id")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"uid" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "users_uid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"email" text NOT NULL,
	"name" text
);
--> statement-breakpoint
ALTER TABLE "sprint_task_events" ADD CONSTRAINT "sprint_task_events_sprint_id_sprints_uid_fk" FOREIGN KEY ("sprint_id") REFERENCES "public"."sprints"("uid") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sprint_task_events" ADD CONSTRAINT "sprint_task_events_task_id_tasks_uid_fk" FOREIGN KEY ("task_id") REFERENCES "public"."tasks"("uid") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sprint_tasks" ADD CONSTRAINT "sprint_tasks_sprint_id_sprints_uid_fk" FOREIGN KEY ("sprint_id") REFERENCES "public"."sprints"("uid") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sprint_tasks" ADD CONSTRAINT "sprint_tasks_task_id_tasks_uid_fk" FOREIGN KEY ("task_id") REFERENCES "public"."tasks"("uid") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sprints" ADD CONSTRAINT "sprints_session_id_focus_sessions_uid_fk" FOREIGN KEY ("session_id") REFERENCES "public"."focus_sessions"("uid") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_project_id_projects_uid_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("uid") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_parent_task_id_tasks_uid_fk" FOREIGN KEY ("parent_task_id") REFERENCES "public"."tasks"("uid") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_client_migrations_applied_at" ON "client_migrations" USING btree ("applied_at");--> statement-breakpoint
CREATE INDEX "idx_sprint_task_events" ON "sprint_task_events" USING btree ("sprint_id","timestamp");--> statement-breakpoint
CREATE UNIQUE INDEX "ux_sprint_task_order" ON "sprint_tasks" USING btree ("sprint_id","ordinal");--> statement-breakpoint
CREATE UNIQUE INDEX "leaf_or_root_only" ON "tasks" USING btree ("uid");--> statement-breakpoint
CREATE INDEX "idx_tasks_parent" ON "tasks" USING btree ("parent_task_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uniq_users_email" ON "users" USING btree ("email");